### ISSUE TITLE
The roadmap of the new version of YGOPro

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2006]
Thanks to the effort of all developers, here is the progress of the new version of YGOPro. I think we can call the new version finished when this progress come to 90%. If I missed anything, please inform me.

 - Link Monsters
   - [x] basic implement
   - [x] can't be target of level related effects
   - [x] can't be target of defense related effects
   - [x] can't change position
     - [x] update of related scripts ( https://github.com/Fluorohydride/ygopro/issues/2002 )
   - [x] functions
     - [x] Card.GetLink，Card.GetLinkedGroup，Card.GetLinkedZone
     - [x] Card.IsLinkState，Card.IsLinkMarker
     - [x] Card.GetMutualLinkedGroup
     - [x] Duel.GetLinkedGroup，Duel.GetLinkedZone
     - [x] Card.IsCanBeLinkMaterial (https://github.com/Fluorohydride/ygopro-core/pull/98 )
 - New Field
   - [x] Extra Monster Zone
     - [x] the check of zone when summoning monsters to main zone using monsters in extra zone (kaiju etc.)
     - [x] other zone check
     - [x] move place
     - [x] control change
   - [x] Pendulum zone
     - [x] related script changes
     - [x] pre activate P cards in single mode
   - [x] draw linked zones
     - [x] draw mutual link status
   - [x] Extra link
     - [ ] draw extra link status
 - Special summoning from extra deck
   - [x] Link
     - [x] basic implement
     - special link summon (OCG don't have such cards yet)
   - [x] Fusion
     - [x] normal
     - [x] Contact Fusion
     - [x] check material without checking zone (https://github.com/Fluorohydride/ygopro/issues/2004 )
   - [x] Synchro
     - [x] normal
     - [x] Double Tuning and other special (https://github.com/Fluorohydride/ygopro-scripts/issues/882 )
   - [x] Xyz
     - [x] normal
     - [x] special (https://github.com/Fluorohydride/ygopro-scripts/issues/882 )
   - [x] Pendulum
     - [x] normal
     - [x] special
     - [x] select place of cards from extra deck before cards from hand
   - [x] other
     - [x] effects that summon monsters from extra deck
   - [x] functions
     - [x] GetLocationCount
     - [x] GetLocationCountFromEx
     - [x] CheckMZoneFromEx
     - [x] GetUsableMZoneCount
 - Updates related to new cards
   - [x] _Trickstar Lightstage_: activation of card in effect (https://github.com/Fluorohydride/ygopro/issues/2005 )
   - [x] _Stargrail Swordsman Aurum_: special summon location check (https://github.com/Fluorohydride/ygopro/issues/2003 )
   - [x] _Transmission Gear_: rock-paper-scissors in duel
   - [x] _Proxy Dragon_: fix https://github.com/Fluorohydride/ygopro/issues/1966
   - [x] _Performapal Odd-Eyes Synchron_: synchro check of cards in pzone
   - [x] _Number 41: Baguska_: fix https://github.com/Fluorohydride/ygopro/issues/1985
   - [x] _Sea Stealth Attack_：: activation of card in effect (https://github.com/Fluorohydride/ygopro/issues/2005 )
   - [x] _Gouki Thunder Ogre_: addition normal summon to specific zones
   - [x] _Varrel Load Dragon_: fix https://github.com/Fluorohydride/ygopro/issues/1984

**Comment by shadowfox87** [comment]
Nice job writing this @mercury233. Also thanks to the whole team and developers who contributed. Great work!

**Comment by johnsonalpha** [comment]
awesome
