### ISSUE TITLE
issues of effects that change battle damage

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro#2255]
### summary of the rulings: 
after calculating atk and def:
1. first calculate "inflict double battle damage" of ブルーアイズ・カオス・MAX・ドラゴン/_Blue-Eyes Chaos MAX Dragon_, etc
2. then calculate "inflict battle damage to both player" of 脆刃の剣, etc
3. then calculate "your opponent takes battle damage instead" of アマゾネスの剣士/_Amazoness Swords Woman_ and "also inflict battle damage to your opponent" of LL－リサイト・スターリング/_Lyrilusc - Recital Starling_ and "take battle damage your opponent would have taken" of ボイコットン/_Boycotton_
multiple such effects will only be applied once
4. then calculate "double battle damage" "half battle damage" of アクションマジック－フルターン/_Action Magic - Full Turn_ and No.73 激瀧神アビス・スプラッシュ/_Number 73: Abyss Splash_
multiple double or half will only be applied once, both double and half will cancel out
5. then calculate "battle damage become..." of 和睦の使者/_Waboku_ 心眼の祭殿/_Temple of the Mind's Eye_
becoming 0 has higher priority that becoming other point, https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21270&keyword=&tag=-1
6. if there is "recover battle damage" of レインボー・ライフ/_Rainbow Life_, recover the point calculated above

ref (Chinese): https://ocg-rule.readthedocs.io/zh_CN/latest/c02/%E6%88%98%E6%96%97%E9%98%B6%E6%AE%B5%E6%B5%81%E7%A8%8B.html#id15 
based on many mails

### plan

- [x] update `EFFECT_PIERCE` to support inflicting double piecing battle damage Fluorohydride/ygopro-core#259

- [x] add `EFFECT_BOTH_BATTLE_DAMAGE`, `EFFECT_ALSO_BATTLE_DAMAGE` Fluorohydride/ygopro-core#263

- [x] add `EFFECT_CHANGE_BATTLE_DAMAGE`, support changing battle damage to specific point or double/half battle damage Fluorohydride/ygopro-core#268

related issue: #2245 #1871
